services:
  php:
    build:
      context: .docker
      dockerfile: Dockerfile
    container_name: php-typed-pattern-engine
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    environment:
      - XDEBUG_MODE=debug,coverage
      - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9000 start_with_request=yes
      - PHP_IDE_CONFIG=serverName=ddev
    expose:
      - "9000"
    stdin_open: true
    tty: true
